---
# tasks file for ansible-provision-rpis


#- name: Debug Gathered Facts
#  debug:
#    var: item
#  with_items:
#    - "{{ ansible_lsb }}"
#    - "{{ ansible_default_ipv4 }}"
#    - "{{ ansible_date_time }}"
#    - "{{ ansible_dns }}"
#    - "{{ ansible_env }}"
#    - "{{ ansible_hostname }}"
#    - "{{ ansible_memory_mb }}"
#    - "{{ ansible_memfree_mb }}"

- name          : Obtener version de Sistema Operativo
  command       : uname -a
  register      : os_name

- name          : Mostrar version de Sistema Operativo
  debug         :
    var         : os_name.stdout

- name          : Configurar Netplan
  include_tasks : netplan.yml
  when          : provision_netplan_configure

- name          : Establecer el nombre de la máquina
  hostname      :
    name        : "{{ provision_hostname }}"

- name          : Asegurarnos de que el grupo 'wheel' existe
  group         :
    name        : wheel
    state       : present

- name          : Comprobar si existe el usuario que hemos indicado para el cluster
  shell         : egrep "^{{ provision_cluster_user }}:" /etc/passwd
  register      : provision_user_exists
  ignore_errors : true

- name          : Crear el usuario con privilegios sudo si no existe
  include_tasks : create_sudo_user.yml
  when          : provision_cluster_user is defined and provision_user_exists.rc == 1

- name          : Permitir a los usuarios del gpo 'wheel' hacer sudo sin password
  lineinfile    :
    path        : /etc/sudoers
    state       : present
    regexp      : '^%wheel'
    line        : '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate    : '/usr/sbin/visudo -cf %s'

- name          : Desactivar por seguridad el acceso por SSH de root
  lineinfile    :
    path        : /etc/ssh/sshd_config
    state       : present
    regexp      : '^PermitRootLogin'
    line        : 'PermitRootLogin no'

      #- name          : Añadir repositorio para instalar Helm
      #  shell         : |
      #                curl https://baltocdn.com/helm/signing.asc | sudo apt-key add - \ 
      #                sudo apt-get install apt-transport-https --yes \
      #                echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

- name          : Actualizar apt
  apt           : 
    update_cache: yes
    force_apt_get: yes

- name          : Esperar si APT se encuentra bloqueado
  shell         : while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name          : Instalar paquetes indicados
  apt           : name={{ provision_rpis_packages }} state=latest force_apt_get=yes


- name          : Instalar Helm mediante snap
  command       : "sudo snap install helm --classic"

- name          : Añadir líneas en etc_hosts para que se vean entre sí
  blockinfile   :
    path        : /etc/hosts
    block       : |
                {{ item.ip }} {{ item.name }}
    marker      : "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items    : '{{ provision_rpis_cluster }}'

- name          : Instalar y configurar Postfix
  include_tasks : postfix.yml
  when          : provision_postfix

- name          : Generar certificado autofirmado de Master
  include_tasks : master_cert.yml
  when          : kubernetes_role == 'master' and provision_master_selfcert

#Exportar directorios desde Master por NFS
- name          : Exportar carpetas de Master por NFS
  include_tasks : nfs_export.yml
  when          : provision_nfs_master_exports is defined and kubernetes_role == 'master'

#Montar directorios anteriores
- name          : Montar carpetas NFS
  include_tasks : nfs_mount.yml
  when          : provision_nfs_host_mount or provision_master_nfs2nodes

- name          : Instalar certificado de Master en todas las maquinas
  include_tasks : install_cert.yml
  when          : provision_master_selfcert

- name          : Deshabilitar swap si así se requiere
  include_tasks : disable_swap.yml
  when          : provision_disable_swap

# vim: ff=unix:ai:et:sw=2:ts=2:
