---


### https://docs.docker.com/engine/security/https/ ###

- name          : Crear carpeta para certificados
  file          :
    path        : "/opt/certs"
    state       : directory
    owner       : root
    group       : wheel

- name          : Master CA cert
  command       : "openssl genrsa -passout pass:{{ provision_master_cert_passwd }} -aes256 -out /opt/certs/ca.pem 4096"
  args          :
    creates     : "/opt/certs/ca.pem"

- name          : Generar Master cert
  command       : "openssl req -newkey rsa:4096 -nodes -sha256 -keyout /opt/certs/registry.key -x509 -days 365 -subj \"/C=ES/ST=GC/L=GC/O=ITC/OU=ITD/CN=master\" -out /opt/certs/registry.crt"
  args          :
    creates     : "/opt/certs/registry.crt"

- name          : Copiar certificado con extension cert
  command       : "cp /opt/certs/registry.crt /opt/certs/registry.cert"
  args          :
    creates     : "/opt/certs/registry.cert"

# vim: ff=unix:ai:et:sw=2:ts=2:
