---

- name: Ensure directories to export exist
  file: 
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ provision_nfs_master_exports }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: exports_file

- name: reload nfs
  command: 'exportfs -ra'
  when: exports_file is changed

- name: Ensure nfs is running.
  service: "name=nfs-kernel-server state=started enabled=yes"
  when: provision_nfs_master_exports|length

